# Generated by Django 5.0.6 on 2024-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
