# Generated by Django 5.0.6 on 2024-06-23 19:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0005_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='http://res.cloudinary.com/dkzk3c8rt/image/upload/v1719169562/APIs_customers/ja0cm5vzpjjzkzfhkpcs.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
