# Generated by Django 5.0.6 on 2024-06-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0008_rename_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='followers',
            field=models.ManyToManyField(related_name='followedby', to='APIs.customer'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
