# Generated by Django 5.0.6 on 2024-06-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0009_customer_followers_post_comments_post_dislikes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='followers',
            new_name='following',
        ),
    ]
